---

- hosts: all
  tasks:

  - name: update cache
    apt:
      update_cache: yes

  - name: Install Apache2 in ubuntu
    apt:
      name: apache2
      state: present

  - name: Set timezone to Africa/Lagos
    timezone:
      name: Africa/Lagos

  - name: Display hostname of webservers
    shell: echo "<h1>Hello, welcome to my web server This is $(hostname -f) Today's date is $(date)</h1>" > /var/www/html/index.html
    notify: restart_apache

  handlers:
  - name: restart_apache
    systemd:
      name: apache2
      state: restarted



